# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-21 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='\u0412\u0440\u0435\u043c\u044f')),
                ('name', models.CharField(max_length=255, verbose_name='\u0421\u043e\u0431\u044b\u0442\u0438\u0435')),
                ('details', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0414\u0435\u0442\u0430\u043b\u0438')),
                ('domain', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0414\u043e\u043c\u0435\u043d')),
            ],
        ),
    ]
