# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 12:43
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u0422\u0435\u043c\u0430')),
                ('body', ckeditor.fields.RichTextField(verbose_name='\u0422\u0435\u043a\u0441\u0442')),
                ('pptx', models.FileField(upload_to=b'', verbose_name='\u041f\u0440\u0435\u0437\u0435\u043d\u0442\u0430\u0446\u0438\u044f')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Course', verbose_name='\u041a\u0443\u0440\u0441')),
            ],
        ),
    ]
