# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='avatar',
            field=models.FileField(default=b'avatars/anon.jpg', upload_to=b'avatars', verbose_name='\u0410\u0432\u0430\u0442\u0430\u0440'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='courses', to='students.Teacher', verbose_name='\u041f\u0440\u0435\u043f\u043e\u0434\u0430\u0432\u0430\u0442\u0435\u043b\u0438'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='students.Course', verbose_name='\u041a\u0443\u0440\u0441'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.Group', verbose_name='\u0413\u0440\u0443\u043f\u043f\u0430'),
        ),
    ]
