# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20160916_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[(b'spring', '\u0412\u0435\u0441\u0435\u043d\u043d\u0438\u0439'), (b'summer', '\u041b\u0435\u0442\u043d\u0438\u0439'), (b'fall', '\u041e\u0441\u0435\u043d\u043d\u0438\u0439'), (b'winter', '\u0417\u0438\u043c\u043d\u0438\u0439')], max_length=10, verbose_name='\u0421\u0435\u043c\u0435\u0441\u0442\u0440'),
        ),
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.FileField(upload_to=b'avatars/', verbose_name='\u0410\u0432\u0430\u0442\u0430\u0440'),
        ),
    ]
