# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20160917_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='avatar',
            field=models.FileField(null=True, upload_to=b'avatars/', verbose_name='\u0410\u0432\u0430\u0442\u0430\u0440'),
        ),
    ]
