# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 14:19
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20160917_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u0422\u0435\u043c\u0430')),
                ('body', ckeditor.fields.RichTextField(verbose_name='\u0422\u0435\u043a\u0441\u0442')),
                ('deadline', models.DateTimeField(verbose_name='\u041a\u0440\u0430\u0439\u043d\u0438\u0439 \u0441\u0440\u043e\u043a \u0441\u0434\u0430\u0447\u0438')),
                ('active', models.BooleanField(default=True, verbose_name='\u0410\u043a\u0442\u0438\u0432\u0435\u043d')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labworks', to='students.Course', verbose_name='\u041a\u0443\u0440\u0441')),
            ],
        ),
        migrations.AlterField(
            model_name='group',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='groups', to='students.Course', verbose_name='\u041a\u0443\u0440\u0441\u044b'),
        ),
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to=b'avatars/', verbose_name='\u0410\u0432\u0430\u0442\u0430\u0440'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to=b'avatars/', verbose_name='\u0410\u0432\u0430\u0442\u0430\u0440'),
        ),
    ]
