# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 15:36
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20160923_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=b'', verbose_name='\u0424\u0430\u0439\u043b')),
                ('comment', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='\u041a\u043e\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439')),
                ('labwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.LabWork', verbose_name='\u0420\u0430\u0431\u043e\u0442\u0430')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student', verbose_name='\u0421\u0442\u0443\u0434\u0435\u043d\u0442')),
            ],
        ),
    ]
