# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 03:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_auto_20160924_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='color',
            field=models.CharField(default=b'#ff1493', max_length=20, verbose_name='\u0426\u0432\u0435\u0442'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='color',
            field=models.CharField(default=b'#f44336', max_length=20, verbose_name='\u0426\u0432\u0435\u0442'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='students.Course', verbose_name='\u041a\u0443\u0440\u0441'),
        ),
    ]
