# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_auto_20160925_0303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
                ('name', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
        ),
        migrations.CreateModel(
            name='StudentMedal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.Course', verbose_name='\u0417\u0430 \u043a\u0443\u0440\u0441')),
                ('medal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medals', to='students.Medal', verbose_name='\u041c\u0435\u0434\u0430\u043b\u044c')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medals', to='students.Student', verbose_name='\u0421\u0442\u0443\u0434\u0435\u043d\u0442')),
            ],
        ),
    ]
