# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_medal_studentmedal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipients', models.TextField(verbose_name='\u041a \u043a\u043e\u043c\u0443(json array)')),
                ('body_html', models.TextField(verbose_name='\u0422\u0435\u043b\u043e \u0441\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u044f (html)')),
                ('body_txt', models.TextField(verbose_name='\u0422\u0435\u043b\u043e \u0441\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u044f (txt)')),
                ('subject', models.CharField(max_length=255, verbose_name='\u0422\u0435\u043c\u0430')),
            ],
        ),
    ]
