# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='labwork',
            name='number',
            field=models.IntegerField(default=0, verbose_name='\u041d\u043e\u043c\u0435\u0440'),
        ),
    ]
