# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 10:32
from __future__ import unicode_literals

import datetime

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('students', '0015_labwork_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439')),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u0412\u0440\u0435\u043c\u044f')),
                ('mark', models.IntegerField(default=0, verbose_name='\u0411\u0430\u043b\u043b\u044b')),
            ],
            options={
                'verbose_name': '\u0420\u0435\u0448\u0435\u043d\u0438\u0435',
                'verbose_name_plural': '\u0420\u0435\u0448\u0435\u043d\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u044f')),
                ('active', models.BooleanField(default=True, verbose_name='\u0410\u043a\u0442\u0438\u0432\u0435\u043d')),
                ('title', models.CharField(max_length=255, verbose_name='\u0422\u0435\u043c\u0430')),
                ('body', ckeditor.fields.RichTextField(verbose_name='\u0422\u0435\u043a\u0441\u0442')),
            ],
            options={
                'verbose_name': '\u0417\u0430\u0434\u0430\u043d\u0438\u0435',
                'verbose_name_plural': '\u0417\u0430\u0434\u0430\u043d\u0438\u044f',
            },
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'verbose_name': '\u0421\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0435 \u0447\u0430\u0442\u0430', 'verbose_name_plural': '\u0421\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u044f \u0447\u0430\u0442\u0430'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '\u041a\u0443\u0440\u0441', 'verbose_name_plural': '\u041a\u0443\u0440\u0441\u044b'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': '\u0413\u0440\u0443\u043f\u043f\u0430', 'verbose_name_plural': '\u0413\u0440\u0443\u043f\u043f\u044b'},
        ),
        migrations.AlterModelOptions(
            name='lecture',
            options={'verbose_name': '\u041b\u0435\u043a\u0446\u0438\u044f', 'verbose_name_plural': '\u041b\u0435\u043a\u0446\u0438\u0438'},
        ),
        migrations.AlterModelOptions(
            name='mail',
            options={'verbose_name': '\u041f\u043e\u0447\u0442\u0430', 'verbose_name_plural': '\u041f\u043e\u0447\u0442\u044b'},
        ),
        migrations.AlterModelOptions(
            name='medal',
            options={'verbose_name': '\u0412\u0438\u0434 \u043c\u0435\u0434\u0430\u043b\u0438', 'verbose_name_plural': '\u0412\u0438\u0434\u044b \u043c\u0435\u0434\u0430\u043b\u0435\u0439'},
        ),
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': '\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c', 'verbose_name_plural': '\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u0438'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '\u0421\u0442\u0443\u0434\u0435\u043d\u0442', 'verbose_name_plural': '\u0421\u0442\u0443\u0434\u0435\u043d\u0442\u044b'},
        ),
        migrations.AlterModelOptions(
            name='studentmedal',
            options={'verbose_name': '\u041c\u0435\u0434\u0430\u043b\u044c', 'verbose_name_plural': '\u041c\u0435\u0434\u0430\u043b\u0438'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': '\u041f\u0440\u0435\u043f\u043e\u0434\u0430\u0432\u0430\u0442\u0435\u043b\u044c', 'verbose_name_plural': '\u041f\u0440\u0435\u043f\u043e\u0434\u0430\u0432\u0430\u0442\u0435\u043b\u0438'},
        ),
        migrations.CreateModel(
            name='FileResolution',
            fields=[
                ('resolution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='students.Resolution')),
                ('file', models.FileField(upload_to=b'', verbose_name='\u0424\u0430\u0439\u043b')),
            ],
            options={
                'verbose_name': '\u0420\u0435\u0448\u0435\u043d\u0438\u0435 \u0441 \u0444\u0430\u0439\u043b\u043e\u043c',
                'verbose_name_plural': '\u0420\u0435\u0448\u0435\u043d\u0438\u044f \u0441 \u0444\u0430\u0439\u043b\u043e\u043c',
            },
            bases=('students.resolution',),
        ),
        migrations.CreateModel(
            name='LabTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='students.Task')),
                ('number', models.IntegerField(default=0, verbose_name='\u041d\u043e\u043c\u0435\u0440')),
                ('deadline', models.DateTimeField(verbose_name='\u041a\u0440\u0430\u0439\u043d\u0438\u0439 \u0441\u0440\u043e\u043a \u0441\u0434\u0430\u0447\u0438')),
            ],
            options={
                'verbose_name': '\u041b\u0430\u0431\u043e\u0440\u0430\u0442\u043e\u0440\u043d\u0430\u044f \u0440\u0430\u0431\u043e\u0442\u0430',
                'verbose_name_plural': '\u041b\u0430\u0431\u043e\u0440\u0430\u0442\u043e\u0440\u043d\u044b\u0435 \u0440\u0430\u0431\u043e\u0442\u044b',
            },
            bases=('students.task',),
        ),
        migrations.AddField(
            model_name='task',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='students.Course', verbose_name='\u041a\u0443\u0440\u0441'),
        ),
        migrations.AddField(
            model_name='task',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_students.task_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='resolution',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_students.resolution_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='resolution',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='students.Student', verbose_name='\u0421\u0442\u0443\u0434\u0435\u043d\u0442'),
        ),
        migrations.AddField(
            model_name='resolution',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='students.Task', verbose_name='\u0417\u0430\u0434\u0430\u043d\u0438\u0435'),
        ),
    ]
