# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 10:32
from __future__ import unicode_literals

from django.db import migrations


class DataMigraton:

    @staticmethod
    def migrate_old_labs_and_solutions_data(apps, schema_editor):
        LabWork = apps.get_model("students", "LabWork")
        LabTask = apps.get_model("students", "LabTask")
        ContentType = apps.get_model('contenttypes', 'ContentType')
        lab_task_ctype = ContentType.objects.get_for_model(LabTask)
        for lab_work in LabWork.objects.all():
            task = LabTask(number=lab_work.number, course=lab_work.course, title=lab_work.title, body=lab_work.body)
            task.deadline = lab_work.deadline
            task.active = lab_work.active
            task.polymorphic_ctype = lab_task_ctype
            task.save()
        Solution = apps.get_model("students", "Solution")
        FileResolution = apps.get_model("students", "FileResolution")
        file_resolution_ctype = ContentType.objects.get_for_model(FileResolution)
        for solution in Solution.objects.all():
            task = DataMigraton.find_lab_task_for(apps, solution.labwork)
            if task:
                file_resolution = FileResolution(comment=solution.comment, task=task, student=solution.student)
                file_resolution.datetime = solution.datetime
                file_resolution.mark = solution.mark
                file_resolution.file.name = solution.file.name
                file_resolution.polymorphic_ctype = file_resolution_ctype
                file_resolution.save()

    @staticmethod
    def do_nothing(apps, schema_editor):
        pass

    @staticmethod
    def find_lab_task_for(apps, labwork):
        LabTask = apps.get_model("students", "LabTask")
        tasks = LabTask.objects.filter(title=labwork.title)
        if tasks.count() > 0:
            return tasks.all()[0]
        return None


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('students', '0016_auto_20161020_1032'),
    ]

    operations = [
        migrations.RunPython(DataMigraton.migrate_old_labs_and_solutions_data, DataMigraton.do_nothing),
    ]
