# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 12:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_migrate_old_labs_and_solutions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labwork',
            name='course',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='labwork',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='student',
        ),
        migrations.DeleteModel(
            name='LabWork',
        ),
        migrations.DeleteModel(
            name='Solution',
        ),
    ]
