# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_auto_20161020_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='color',
            field=models.CharField(default=b'#dff0d8', max_length=20, verbose_name='\u0426\u0432\u0435\u0442'),
        ),
        migrations.AddField(
            model_name='task',
            name='important',
            field=models.BooleanField(default=False, verbose_name='\u0412\u0430\u0436\u043d\u043e\u0435'),
        ),
        migrations.AddField(
            model_name='task',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u044f'),
        ),
    ]
