# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('students', '0019_auto_20161020_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadConstraint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileNameConstraint',
            fields=[
                ('uploadconstraint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='students.UploadConstraint')),
                ('extension', models.CharField(blank=True, help_text='\u041e\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u043f\u0443\u0441\u0442\u044b\u043c, \u0435\u0441\u043b\u0438 \u043d\u0435\u0442 \u043e\u0433\u0440\u0430\u043d\u0438\u0447\u0435\u043d\u0438\u0439', max_length=20, null=True, verbose_name='\u0422\u0440\u0435\u0431\u0443\u0435\u043c\u043e\u0435 \u0440\u0430\u0441\u0448\u0438\u0440\u0435\u043d\u0438\u0435 \u0444\u0430\u0439\u043b\u0430')),
                ('file_name', models.CharField(blank=True, help_text='\u041e\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u043f\u0443\u0441\u0442\u044b\u043c, \u0435\u0441\u043b\u0438 \u043d\u0435\u0442 \u043e\u0433\u0440\u0430\u043d\u0438\u0447\u0435\u043d\u0438\u0439', max_length=255, null=True, verbose_name='\u0422\u0440\u0435\u0431\u0443\u0435\u043c\u043e\u0435 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0444\u0430\u0439\u043b\u0430')),
            ],
            options={
                'abstract': False,
            },
            bases=('students.uploadconstraint',),
        ),
        migrations.CreateModel(
            name='FileSizeConstraint',
            fields=[
                ('uploadconstraint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='students.UploadConstraint')),
                ('max_size', models.CharField(default=b'5M', help_text='\u0424\u043e\u0440\u043c\u0430\u0442\u044b: 12K, 300B, 5M', max_length=100, verbose_name='\u041c\u0430\u043a\u0441\u0438\u043c\u0430\u043b\u044c\u043d\u044b\u0439 \u0440\u0430\u0437\u043c\u0435\u0440 \u0444\u0430\u0439\u043b\u0430')),
                ('min_size', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u041c\u0438\u043d\u0438\u0438\u043c\u0430\u043b\u044c\u043d\u044b\u0439 \u0440\u0430\u0437\u043c\u0435\u0440 \u0444\u0430\u0439\u043b\u0430')),
            ],
            options={
                'abstract': False,
            },
            bases=('students.uploadconstraint',),
        ),
        migrations.CreateModel(
            name='ZipContainsFileConstraint',
            fields=[
                ('uploadconstraint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='students.UploadConstraint')),
                ('file_names', models.CharField(help_text='\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0444\u0430\u0439\u043b\u043e\u0432 \u0447\u0435\u0440\u0435\u0437 \u0437\u0430\u043f\u044f\u0442\u0443\u044e', max_length=1000, verbose_name='\u041a\u0430\u043a\u0438\u0435 \u0444\u0430\u0439\u043b\u044b \u0434\u043e\u043b\u0436\u0435\u043d \u0441\u043e\u0434\u0435\u0440\u0436\u0430\u0442\u044c zip-\u0430\u0440\u0445\u0438\u0432')),
            ],
            options={
                'abstract': False,
            },
            bases=('students.uploadconstraint',),
        ),
        migrations.CreateModel(
            name='ZipFileConstraint',
            fields=[
                ('uploadconstraint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='students.UploadConstraint')),
            ],
            options={
                'abstract': False,
            },
            bases=('students.uploadconstraint',),
        ),
        migrations.AddField(
            model_name='uploadconstraint',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_students.uploadconstraint_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='uploadconstraint',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.LabTask', verbose_name='\u041b\u0430\u0431\u043e\u0440\u0430\u0442\u043e\u0440\u043d\u0430\u044f \u0440\u0430\u0431\u043e\u0442\u0430'),
        ),
    ]
