# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-23 20:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_auto_20161111_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastReadMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_message_id', models.IntegerField(blank=True, default=0, verbose_name='\u041f\u043e\u0441\u043b\u0435\u0434\u043d\u0435\u0435 \u043f\u0440\u043e\u0447\u0438\u0442\u0430\u043d\u043d\u043e\u0435 \u0441\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0435')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Course', verbose_name='\u0427\u0430\u0442 \u043a\u0430\u043a\u043e\u0433\u043e \u043a\u0443\u0440\u0441\u0430')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c')),
            ],
        ),
    ]
