# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-24 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_lastreadmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u041f\u043e\u0441\u043b\u0435\u0434\u043d\u0438\u0439 \u0432\u0438\u0437\u0438\u0442'),
        ),
    ]
