# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-29 23:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0024_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_students_rel', to='students.Course', verbose_name='\u041a\u0443\u0440\u0441')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student', verbose_name='\u0421\u0442\u0443\u0434\u0435\u043d\u0442')),
            ],
            options={
                'verbose_name': '\u0421\u0442\u0443\u0434\u0435\u043d\u0442 \u0437\u0430\u043f\u0438\u0441\u0430\u0432\u0448\u0438\u0439\u0441\u044f \u043d\u0435 \u043d\u0430 \u0441\u0432\u043e\u0439 \u043a\u0443\u0440\u0441',
                'verbose_name_plural': '\u0421\u0442\u0443\u0434\u0435\u043d\u0442\u044b \u0437\u0430\u043f\u0438\u0441\u0430\u0432\u0448\u0438\u0435\u0441\u044f \u043d\u0435 \u043d\u0430 \u0441\u0432\u043e\u0438 \u043a\u0443\u0440\u0441\u044b',
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='students.Course', verbose_name='\u041a\u0443\u0440\u0441'),
        ),
    ]
