# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-01 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0025_auto_20170129_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='viewed_mobile',
            field=models.IntegerField(default=0, verbose_name='\u041f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0435\u043d\u043e \u0447\u0435\u0440\u0435\u0437 \u043f\u0440\u0438\u043b\u043e\u0436\u0435\u043d\u0438\u0435'),
        ),
    ]
