# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-06 22:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0026_article_viewed_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='\u0422\u0435\u043a\u0441\u0442')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='\u0412\u0440\u0435\u043c\u044f')),
                ('color', models.CharField(default=b'#FFFFFF', max_length=20, verbose_name='\u0426\u0432\u0435\u0442')),
                ('done', models.BooleanField(default=False, verbose_name='\u0414\u043e\u0441\u0442\u0438\u0433\u043d\u0443\u0442\u043e')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c')),
            ],
        ),
        migrations.AlterField(
            model_name='extrastudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_courses_rel', to='students.Student', verbose_name='\u0421\u0442\u0443\u0434\u0435\u043d\u0442'),
        ),
    ]
