# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-12 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0028_fileresolution_index_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255, verbose_name='\u0417\u0430 \u0447\u0442\u043e')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='\u0412\u0440\u0435\u043c\u044f')),
                ('points', models.IntegerField(default=0, verbose_name='\u041e\u0447\u043a\u0438')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Course', verbose_name='\u041a\u0443\u0440\u0441')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='students.Student', verbose_name='\u0421\u0442\u0443\u0434\u0435\u043d\u0442')),
            ],
        ),
    ]
