# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-12 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0029_point'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='point',
            options={'verbose_name': '\u041e\u0447\u043a\u0438 \u043e\u043f\u044b\u0442\u0430', 'verbose_name_plural': '\u041e\u0447\u043a\u0438 \u043e\u043f\u044b\u0442\u0430'},
        ),
    ]
