# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-16 19:56
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0030_auto_20170212_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeWorkSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(help_text='\u041a\u0430\u043a\u043e\u0435 \u0431\u044b\u043b\u043e \u0437\u0430\u0434\u0430\u043d\u0438\u0435?', max_length=255, verbose_name='\u0417\u0430\u0434\u0430\u043d\u0438\u0435')),
                ('comment', ckeditor.fields.RichTextField(help_text='\u041e\u043f\u0438\u0448\u0438\u0442\u0435 \u043a\u0430\u043a \u0432\u044b \u0440\u0435\u0448\u0438\u043b\u0438, \u0447\u0442\u043e \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u043b\u0438 \u0438 \u0442.\u043f.', verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='\u0412\u0440\u0435\u043c\u044f')),
                ('file', models.FileField(upload_to=b'', verbose_name='\u0424\u0430\u0439\u043b')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Course', verbose_name='\u041a\u0443\u0440\u0441')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='students.Student', verbose_name='\u0421\u0442\u0443\u0434\u0435\u043d\u0442')),
            ],
            options={
                'verbose_name': '\u0420\u0435\u0448\u0435\u043d\u0438\u0435 \u0414\u0417',
                'verbose_name_plural': '\u0420\u0435\u0448\u0435\u043d\u0438\u044f \u0414\u0417',
            },
        ),
    ]
