# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-01 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0032_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
