# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-12 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0033_feedback_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u043c\u0430\u0442\u0435\u0440\u0438\u0430\u043b'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='pptx',
            field=models.FileField(blank=True, null=True, upload_to=b'', verbose_name='\u041f\u0440\u0435\u0437\u0435\u043d\u0442\u0430\u0446\u0438\u044f'),
        ),
    ]
