# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-20 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0038_auto_20171009_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtask',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=b'', verbose_name='\u041f\u0440\u0438\u043b\u043e\u0436\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='literature',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='literature', to='students.Course', verbose_name='\u041a\u0443\u0440\u0441'),
        ),
    ]
