# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-08 22:35
from __future__ import unicode_literals

from django.db import migrations, models


def create_slugs(*args, **kwargs):
    from students.model.blog import Article
    from students.model.base import Subject

    for article in Article.objects.all():
        article.save()

    for subject in Subject.objects.all():
        subject.save()


def do_nothing(*args, **kwargs):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0040_auto_20180103_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-datetime'], 'verbose_name': '\u0421\u0442\u0430\u0442\u044c\u044f', 'verbose_name_plural': '\u0421\u0442\u0430\u0442\u044c\u0438'},
        ),
        migrations.AddField(
            model_name='article',
            name='private',
            field=models.BooleanField(default=False, verbose_name='\u041f\u0440\u0438\u0432\u0430\u0442\u043d\u0430\u044f \u0441\u0442\u0430\u0442\u044c\u044f'),
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='subject',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430'),
        ),
        migrations.RunPython(create_slugs, do_nothing)
    ]
