# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-05 16:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0041_auto_20180208_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlreadyKnow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='\u0412\u0440\u0435\u043c\u044f')),
            ],
            options={
                'verbose_name': '\u0421\u0442\u0443\u0434\u0435\u043d\u0442 \u0443\u0436\u0435 \u0437\u043d\u0430\u0435\u0442',
                'verbose_name_plural': '\u0422\u043e, \u0447\u0442\u043e \u0441\u0442\u0443\u0434\u0435\u043d\u0442 \u0443\u0436\u0435 \u0437\u043d\u0430\u0435\u0442',
            },
        ),
        migrations.CreateModel(
            name='MustKnow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.FloatField(default=0, verbose_name='\u041f\u043e\u0440\u044f\u0434\u043e\u043a')),
                ('text', models.CharField(max_length=255, verbose_name='\u0427\u0442\u043e \u0434\u043e\u043b\u0436\u0435\u043d \u0437\u043d\u0430\u0442\u044c \u0441\u0442\u0443\u0434\u0435\u043d\u0442?')),
            ],
            options={
                'verbose_name': '\u0422\u043e, \u0447\u0442\u043e \u0434\u043e\u043b\u0436\u0435\u043d \u0437\u043d\u0430\u0442\u044c \u0441\u0442\u0443\u0434\u0435\u043d\u0442',
                'verbose_name_plural': '\u0422\u043e, \u0447\u0442\u043e \u0434\u043e\u043b\u0436\u0435\u043d \u0437\u043d\u0430\u0442\u044c \u0441\u0442\u0443\u0434\u0435\u043d\u0442',
            },
        ),
        migrations.CreateModel(
            name='MustKnowGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.FloatField(default=0, verbose_name='\u041f\u043e\u0440\u044f\u0434\u043e\u043a')),
                ('name', models.CharField(max_length=100, verbose_name='\u0413\u0440\u0443\u043f\u043f\u0430 \u0437\u043d\u0430\u043d\u0438\u0439')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Course', verbose_name='\u041a\u0443\u0440\u0441')),
            ],
            options={
                'verbose_name': '\u0413\u0440\u0443\u043f\u043f\u0430 \u0437\u043d\u0430\u043d\u0438\u0439 \u043a\u0443\u0440\u0441\u0430',
                'verbose_name_plural': '\u0413\u0440\u0443\u043f\u043f\u044b \u0437\u043d\u0430\u043d\u0438\u0439 \u043a\u0443\u0440\u0441\u0430',
            },
        ),
        migrations.AddField(
            model_name='mustknow',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='students.MustKnowGroup', verbose_name='\u0413\u0440\u0443\u043f\u043f\u0430'),
        ),
        migrations.AddField(
            model_name='alreadyknow',
            name='must_know',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.MustKnow'),
        ),
        migrations.AddField(
            model_name='alreadyknow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='i_know', to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c'),
        ),
    ]
