# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-02 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0042_auto_20180405_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mustknow',
            options={'ordering': ['order'], 'verbose_name': '\u0422\u043e, \u0447\u0442\u043e \u0434\u043e\u043b\u0436\u0435\u043d \u0437\u043d\u0430\u0442\u044c \u0441\u0442\u0443\u0434\u0435\u043d\u0442', 'verbose_name_plural': '\u0422\u043e, \u0447\u0442\u043e \u0434\u043e\u043b\u0436\u0435\u043d \u0437\u043d\u0430\u0442\u044c \u0441\u0442\u0443\u0434\u0435\u043d\u0442'},
        ),
        migrations.AlterModelOptions(
            name='mustknowgroup',
            options={'ordering': ['order'], 'verbose_name': '\u0413\u0440\u0443\u043f\u043f\u0430 \u0437\u043d\u0430\u043d\u0438\u0439 \u043a\u0443\u0440\u0441\u0430', 'verbose_name_plural': '\u0413\u0440\u0443\u043f\u043f\u044b \u0437\u043d\u0430\u043d\u0438\u0439 \u043a\u0443\u0440\u0441\u0430'},
        ),
        migrations.AddField(
            model_name='student',
            name='active',
            field=models.BooleanField(default=True, verbose_name='\u0410\u043a\u0442\u0438\u0432\u0435\u043d'),
        ),
        migrations.AlterField(
            model_name='mustknowgroup',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='must_know_groups', to='students.Course', verbose_name='\u041a\u0443\u0440\u0441'),
        ),
    ]
