# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-10-26 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0043_auto_20180502_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworksolution',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
