# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-12 12:26
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('judge_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ACM Timus Judge ID')),
                ('username', models.CharField(max_length=100, verbose_name='ACM username')),
                ('url', models.CharField(blank=True, max_length=500, null=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c')),
            ],
            options={
                'verbose_name': '\u0423\u0447\u0430\u0441\u0442\u043d\u0438\u043a',
                'verbose_name_plural': '\u0423\u0447\u0430\u0441\u0442\u043d\u0438\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('body', ckeditor.fields.RichTextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('limits', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='\u041e\u0433\u0440\u0430\u043d\u0438\u0447\u0435\u043d\u0438\u044f')),
                ('acm_id', models.IntegerField(verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0437\u0430\u0434\u0430\u0447\u0438')),
                ('difficulty', models.IntegerField(default=0, verbose_name='\u0421\u043b\u043e\u0436\u043d\u043e\u0441\u0442\u044c')),
                ('url', models.CharField(max_length=500, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430')),
            ],
            options={
                'verbose_name': '\u0417\u0430\u0434\u0430\u0447\u0430',
                'verbose_name_plural': '\u0417\u0430\u0434\u0430\u0447\u0438',
            },
        ),
        migrations.CreateModel(
            name='ProblemSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acm_id', models.IntegerField(blank=True, null=True, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u043f\u043e\u043f\u044b\u0442\u043a\u0438')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='\u0412\u0440\u0435\u043c\u044f')),
                ('check_result', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u0420\u0435\u0437\u0443\u043b\u044c\u0442\u0430\u0442 \u043f\u0440\u043e\u0432\u0435\u0440\u043a\u0438')),
                ('language', models.CharField(max_length=100, verbose_name='\u042f\u0437\u044b\u043a')),
                ('test_number', models.IntegerField(blank=True, null=True, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u0441\u0442\u0430')),
                ('time', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u0440\u0430\u0431\u043e\u0442\u044b')),
                ('memory', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u0412\u044b\u0434\u0435\u043b\u0435\u043d\u043e \u043f\u0430\u043c\u044f\u0442\u0438')),
                ('success', models.BooleanField(default=False, verbose_name='\u0420\u0435\u0448\u0435\u043d\u043e')),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Contestant', verbose_name='\u0423\u0447\u0430\u0441\u0442\u043d\u0438\u043a')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Problem', verbose_name='\u0417\u0430\u0434\u0430\u0447\u0430')),
            ],
            options={
                'verbose_name': '\u0420\u0435\u0448\u0435\u043d\u0438\u0435',
                'verbose_name_plural': '\u0420\u0435\u0448\u0435\u043d\u0438\u044f',
            },
        ),
    ]
