# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-14 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemsolution',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='\u041a\u043e\u0434'),
        ),
    ]
