# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-15 19:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_problemsolution_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemsolution',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='\u041f\u0440\u043e\u0432\u0435\u0440\u0435\u043d\u043e'),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contestant', to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c'),
        ),
    ]
