# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-17 17:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coolsnippet',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 11, 17, 0, 0), verbose_name='\u0412\u0440\u0435\u043c\u044f'),
            preserve_default=False,
        ),
    ]
