# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-22 05:58
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cooler', '0003_puzzle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u043e\u0431\u0430\u0432\u043b\u0435\u043d')),
                ('author', models.CharField(max_length=255, verbose_name='\u0410\u0432\u0442\u043e\u0440')),
                ('title', models.CharField(max_length=255, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('body', ckeditor.fields.RichTextField(verbose_name='\u0422\u0435\u043a\u0441\u0442')),
                ('submitted', models.IntegerField(default=0, verbose_name='\u041e\u0442\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u043e')),
                ('accepted', models.IntegerField(default=0, verbose_name='\u0420\u0435\u0448\u0435\u043d\u043e')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseSubmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='\u041e\u0442\u043f\u0440\u0430\u0432\u043b\u0435\u043d')),
                ('code', models.TextField(verbose_name='\u041a\u043e\u0434')),
                ('message', models.CharField(max_length=255, verbose_name='\u0421\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0435')),
                ('accepted', models.BooleanField(default=False, verbose_name='\u0420\u0435\u0448\u0435\u043d\u043e')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='cooler.Exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041e\u0442\u043f\u0440\u0430\u0432\u0438\u043b')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseTestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField(verbose_name='\u0412\u0445\u043e\u0434')),
                ('output', models.TextField(verbose_name='\u0412\u044b\u0445\u043e\u0434')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='cooler.Exercise')),
            ],
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430'),
        ),
    ]
