# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-05 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooler', '0004_auto_20180322_0558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercisesubmit',
            options={'ordering': ['-datetime']},
        ),
    ]
